<?php

namespace DoctrineORMModule\Proxy\__CG__\Godana\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Line extends \Godana\Entity\Line implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'departure', 'arrival', 'zone', 'cooperatives', 'lineContacts');
        }

        return array('__isInitialized__', 'id', 'departure', 'arrival', 'zone', 'cooperatives', 'lineContacts');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Line $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeparture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeparture', array());

        return parent::getDeparture();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeparture($departure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeparture', array($departure));

        return parent::setDeparture($departure);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrival()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrival', array());

        return parent::getArrival();
    }

    /**
     * {@inheritDoc}
     */
    public function setArrival($arrival)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArrival', array($arrival));

        return parent::setArrival($arrival);
    }

    /**
     * {@inheritDoc}
     */
    public function getZone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZone', array());

        return parent::getZone();
    }

    /**
     * {@inheritDoc}
     */
    public function setZone($zone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZone', array($zone));

        return parent::setZone($zone);
    }

    /**
     * {@inheritDoc}
     */
    public function addCooperatives(\Doctrine\Common\Collections\ArrayCollection $cooperatives)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCooperatives', array($cooperatives));

        return parent::addCooperatives($cooperatives);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCooperatives(\Doctrine\Common\Collections\ArrayCollection $cooperatives)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCooperatives', array($cooperatives));

        return parent::removeCooperatives($cooperatives);
    }

    /**
     * {@inheritDoc}
     */
    public function getCooperatives()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCooperatives', array());

        return parent::getCooperatives();
    }

    /**
     * {@inheritDoc}
     */
    public function addCooperative(\Godana\Entity\Cooperative $cooperative)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCooperative', array($cooperative));

        return parent::addCooperative($cooperative);
    }

    /**
     * {@inheritDoc}
     */
    public function addLineContacts(\Doctrine\Common\Collections\ArrayCollection $lineContacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLineContacts', array($lineContacts));

        return parent::addLineContacts($lineContacts);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLineContacts(\Doctrine\Common\Collections\ArrayCollection $lineContacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLineContacts', array($lineContacts));

        return parent::removeLineContacts($lineContacts);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineContacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineContacts', array());

        return parent::getLineContacts();
    }

    /**
     * {@inheritDoc}
     */
    public function addLineContact(\Godana\Entity\LineContact $lineContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLineContact', array($lineContact));

        return parent::addLineContact($lineContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineJourney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineJourney', array());

        return parent::getLineJourney();
    }

}
