<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')?>
<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Car'); ?></h3>
</div>
<div class="panel-body">
<? if ($this->status):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<strong><?= $this->translate('Success!'); ?></strong> <?= $this->translate('Car added successfully.'); ?> 
</div>
<? endif;?>
<?php
$form = $this->carForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/cooperative/car_add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
?>
<?php echo $this->form()->openTag($form) ?>

<? $car = $form->get('car-form'); ?>
<? echo $this->formHidden($car->get('id'));?>
<? $cooperative = $car->get('cooperative'); ?>
<div class="form-group <?php if($this->formElementErrors($cooperative)) 
echo "has-error" ?>">
<?php echo $this->formLabel($cooperative); ?>
<div class="col-sm-7">
<?php echo $this->formElement($cooperative) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($cooperative); ?>
</div>
</div>

<? $make = $car->get('make'); ?>
<div class="form-group <?php if($this->formElementErrors($make)) 
echo "has-error" ?>">
<?php echo $this->formLabel($make); ?>
<div class="col-sm-7">
<?php echo $this->formElement($make) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($make); ?>
</div>
</div>

<? $model = $car->get('model'); ?>
<div class="form-group <?php if($this->formElementErrors($model)) 
echo "has-error" ?>">
<?php echo $this->formLabel($model); ?>
<div class="col-sm-7">
<?php echo $this->formElement($model) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($model); ?>
</div>
</div>

<? $driver = $car->get('driver'); ?>
<div class="form-group <?php if($this->formElementErrors($driver)) 
echo "has-error" ?>">
<?php echo $this->formLabel($driver); ?>
<div class="col-sm-7">
<?php echo $this->formElement($driver) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($driver); ?>
</div>
</div>

<? $license = $car->get('license'); ?>
<div class="form-group <?php if($this->formElementErrors($license)) 
echo "has-error" ?>">
<?php echo $this->formLabel($license); ?>
<div class="col-sm-7">
<?php echo $this->formElement($license) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($license); ?>
</div>
</div>


<? echo $this->formHidden($form->get('csrf'));?>

<div class="form-group">
<div class="col-sm-4 col-sm-offset-3">
<? echo $this->formElement($form->get('submit'));?>
</div>
</div>
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
</div>

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/select2.min.js')?>
			
<script type="text/javascript">
$(function() {
	$(".cooperative-select").select2({
		minimumResultsForSearch: 10
	}).change(function(event) {
		if (event.target == this) {
			var cooperativeId = event.val;
			$(".driver-select").select2({
				placeholder: "Select driver",
				minimumResultsForSearch: 10,
				ajax: {
			        url: "add?cooperativeId="+cooperativeId,
			        dataType: 'json',
			        quietMillis: 100,
			        
			        results: function (data) {
			            return {results: data};
			        }
			    }
			});
		}
	});
	$(".make-select").select2({
		minimumResultsForSearch: 10
	}).change(function(event){
		if(event.target == this){
			var makeId = event.val;
			$(".model-select").select2({
				placeholder: "Select model",
				minimumResultsForSearch: 10,
				ajax: {
			        url: "add?makeId="+makeId,
			        dataType: 'json',
			        quietMillis: 100,
			        
			        results: function (data) {
			            return {results: data};
			        }
			    }
			});
		}
	});
	var cooperativeId = $(".cooperative-select").select2("val");
	$(".driver-select").select2({
		placeholder: "Select driver",
		minimumResultsForSearch: 10,
		ajax: {
	        url: "add?cooperativeId="+cooperativeId,
	        dataType: 'json',
	        quietMillis: 100,
	        
	        results: function (data) {
	            return {results: data};
	        }
	    }
	});

	var makeId = $(".make-select").select2("val");
	$(".model-select").select2({
		placeholder: "Select model",
		minimumResultsForSearch: 10,
		ajax: {
	        url: "add?makeId="+makeId,
	        dataType: 'json',
	        quietMillis: 100,
	        
	        results: function (data) {
	            return {results: data};
	        }
	    }
	});
	function format(item) { return item.text; };
	
});
</script>