<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Car make'); ?></h3>
</div>
<div class="panel-body">
<? if ($this->status):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<strong><?= $this->translate('Success!'); ?></strong> <?= $this->translate('Make added successfully.'); ?> 
</div>
<? endif;?>
<?php
$form = $this->carMakeForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/cooperative/car_make_add', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
?>
<?php echo $this->form()->openTag($form) ?>
<? $carMake = $form->get('car-make-form'); ?>
<? echo $this->formHidden($carMake->get('id'));?>
<? $name = $carMake->get('name'); ?>
<div class="form-group <?php if($this->formElementErrors($name)) 
echo "has-error" ?>">
<?php echo $this->formLabel($name); ?>
<div class="col-sm-7">
<?php echo $this->formElement($name) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($name); ?>
</div>
</div>

<? echo $this->formHidden($form->get('csrf'));?>

<div class="form-group">
<div class="col-sm-4 col-sm-offset-3">
<? echo $this->formElement($form->get('submit'));?>
</div>
</div>
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
</div>