<?php echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/css/select2.css')
                ->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css')?>

<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="panel panel-primary">
<div class="panel-heading">
	<h3 class="panel-title"><?php echo $this->translate('Line'); ?></h3>
</div>
<div class="panel-body">
<? if ($this->status):?>
<div class="alert alert-dismissable alert-success">
<button data-dismiss="alert" class="close">×</button>
<strong><?= $this->translate('Success!'); ?></strong> <?= $this->translate('Line created successfully.'); ?> 
</div>
<? endif;?>
<?php
$form = $this->lineForm;
$form->prepare();
$form->setAttribute('action', $this->url('admin/cooperative/line_create', array('lang' => $this->lang)));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
?>
<?php echo $this->form()->openTag($form) ?>
<? $line = $form->get('line-form'); ?>

<? $zone = $form->get('zone'); ?>
<div class="form-group <?php if($this->formElementErrors($zone)) 
echo "has-error" ?>">
<?php echo $this->formLabel($zone); ?>
<div class="col-sm-7">
<?php echo $this->formElement($zone) ?>
<?php  echo $this->formElementErrors()
	->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>')
    ->render($zone); ?>
</div>
</div>
<? echo $this->formHidden($line->get('id'));?>		
<div class="form-group <?php if($this->formElementErrors($line->get('select-departure'))) 
echo "has-error" ?>">
	<?=$this->formLabel($line->get('select-departure')); ?>
	<div class="col-sm-7">
	<?=$this->formElement($line->get('select-departure')); ?>
	<?=$this->formElementErrors()
		->setMessageOpenFormat('<div class="help-block">')
	    ->setMessageSeparatorString('</div><div class="help-block">')
	    ->setMessageCloseString('</div>')
	    ->render($line->get('select-departure')); ?>
	</div>
</div>
<? echo $this->formHidden($line->get('departure'));?>
<div class="form-group <?php if($this->formElementErrors($line->get('select-arrival'))) 
echo "has-error" ?>">
	<?=$this->formLabel($line->get('select-arrival')); ?>
	<div class="col-sm-7">
	<?=$this->formElement($line->get('select-arrival')); ?>
	<?=$this->formElementErrors()
		->setMessageOpenFormat('<div class="help-block">')
	    ->setMessageSeparatorString('</div><div class="help-block">')
	    ->setMessageCloseString('</div>')
	    ->render($line->get('select-arrival')); ?>
	</div>
</div>
<? echo $this->formHidden($line->get('arrival'));?>
<? echo $this->formHidden($form->get('csrf'));?>

<div class="form-group">
<div class="col-sm-4 col-sm-offset-3">
<? echo $this->formElement($form->get('submit'));?>
</div>
</div>
<?php echo $this->form()->closeTag() ?>
</div>
</div>
</div>
</div>

<? $this->inlineScript()
			->appendFile($this->basePath() . '/js/select2.min.js')?>

<script type="text/javascript">
$(function() {
	$("#select_departure").select2({
		placeholder: "Search for a city",
	    minimumInputLength: 3,
	    ajax: { // instead of writing the function to execute the request we use Select2's convenient helper
	        url: "/admin/shop/city",
	        dataType: 'json',
	        quietMillis: 100,
	        data: function (term, page) {
	            return {
	                q: term, // search term
	                page_limit: 10,
	                page: page, // page number
	            };
	        },
	        results: function (data, page) { // parse the results into the format expected by Select2.
	            // since we are using custom formatting functions we do not need to alter remote JSON data
	            var more = (page * 10) < data.total; // whether or not there are more results available
	            return {results: data.results, more: more};
	        }
//	        results: data
	    },
	    formatSelection: format,
	    formatResult: format
	});
	$('#select_departure').change(function(e) {
		$('#hidden_departure').val($(this).val());
	});

	$("#select_arrival").select2({
		placeholder: "Search for a city",
	    minimumInputLength: 3,
	    ajax: { // instead of writing the function to execute the request we use Select2's convenient helper
	        url: "/admin/shop/city",
	        dataType: 'json',
	        quietMillis: 100,
	        data: function (term, page) {
	            return {
	                q: term, // search term
	                page_limit: 10,
	                page: page, // page number
	            };
	        },
	        results: function (data, page) { // parse the results into the format expected by Select2.
	            // since we are using custom formatting functions we do not need to alter remote JSON data
	            var more = (page * 10) < data.total; // whether or not there are more results available
	            return {results: data.results, more: more};
	        }
//	        results: data
	    },
	    formatSelection: format,
	    formatResult: format
	});
	$('#select_arrival').change(function(e) {
		$('#hidden_arrival').val($(this).val());
	});

	function format(item) { return item.text; };
	$(".chosen-select").select2({
		minimumResultsForSearch: 10
	});
});
</script>